# Generated by Django 3.0.8 on 2020-08-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='srcmodel',
            name='semester',
            field=models.CharField(choices=[('s1', 'semester1'), ('s2', 'semester2')], default='s1', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='srcmodel',
            name='fieldAndLevel',
            field=models.CharField(choices=[('l1', 'licence1'), ('l2', 'licence2'), ('l3', 'licence3'), ('m1', 'master1'), ('m2', 'master2'), ('dc', 'doctorat')], max_length=2),
        ),
    ]
